// Every type emitted by client/ that the Vue build actually acted on.
export const LIVE_TYPES = [
    "ADD_DEFAULT_NOTIFIES", "ADD_HELP_NOTIFY", "ADD_NOTIFY", "ADD_TEXT_UI_ELEMENT",
    "APPLY_EFFECT_ON_INTERFACE", "CHAT_ADD_MESSAGE", "CHAT_ADD_SUGGESTION",
    "CHAT_DUTY_CHANGE", "CHAT_FORCE_HIDE", "CHAT_SET_SERVER_SUGGESTIONS",
    "CHAT_REMOVE_SUGGESTION", "CHAT_SET_INPUT_VISIBLE", "CLEAR_CHAT", "HANDLE_BLACK_SCREEN",
    "HANDLE_MAP_VIEW", "HANDLE_MUSIC", "HANDLE_REGISTER_STATUS_HUD", "HANDLE_SFX_MESSAGE",
    "INDICATE_UNFASTEN_SEATBELT", "LOAD_UP_TRANSLATIONS", "MENU_ON_CHANGE", "ON_MENU_SELECT",
    "OVERRIDE_MUSIC_STATE", "PROGRESS_BAR_INIT", "PROGRESS_BAR_REMOVE", "REMOVE_DEFAULT_NOTIFY",
    "REMOVE_HELP_NOTIFY", "REMOVE_NOTIFY", "REMOVE_STORAGE_FULLY", "REMOVE_TEXT_UI_ELEMENT",
    "SEND_FULL_CFG", "SEND_PAUSEMENU_DATA_BUTTONS", "SET_CARHUD_SEATBELT", "SET_CARHUD_VALUES",
    "SET_CINEMATIC_FOCUS_MODE", "SET_CINEMATIC_MODE_STATE", "SET_COMPONENT_VISIBILITY",
    "SET_MENU_DATA", "SET_MINICOMPONENT_VISIBILITY", "SET_PERSPECTIVE_CONTENT_VISIBILITY",
    "SET_PERSPECTIVE_IN_VEH", "SET_PLAYER_DATA", "SET_PLAYER_STEAM_NAME",
    "SET_PREVIEW_VISIBILITY", "SET_RADAR_SIZE", "SET_RADAR_VISIBILITY", "SET_ROUTER_PATH",
    "SET_SCREEN", "SET_STAGGER_VISIBILITY", "SET_STATUS_VALUE", "SET_STATUS_VISIBILITY",
    "SET_STREETLABEL_DATA", "SET_STREETLABEL_VISIBILITY", "SET_TOP_CONTENT_SCREEN",
    "SET_TOP_CONTENT_VISIBILITY", "SET_UI_DATA_STATUS", "SET_UI_VISIBLE",
    "SET_VOICE_INDICATOR_AS_VISIBLE", "SET_VOICE_INDICATOR_DATA",
    "SET_VOICE_INDICATOR_PLAYER_TALKING", "SET_WEAPON_INDICATOR_AMMO",
    "SET_WEAPON_INDICATOR_AS_ACTIVE", "SET_WEAPON_INDICATOR_NAME", "SHOW_MENU",
    "SHOW_PAUSEMENU", "SHOW_SETTINGS", "UPDATE_CARHUD_VALUE", "UPDATE_DEFAULT_NOTIFY",
    "UPDATE_DEFAULT_NOTIFY_PROGRESS", "UPDATE_HELP_NOTIFY_STAGE", "UPDATE_HELP_NOTIFY_TEXT",
    "UPDATE_HUD_VALUE", "UPDATE_PAUSEMENU", "UPDATE_ROTATIONS", "UPDATE_TEXT_UI_ELEMENT"
];

// Handled by the build but never emitted by this client/; kept as a superset.
export const BUILD_ONLY_TYPES = [
    "CHAT_REMOVE_ALL_SUGGESTIONS", "OBTAIN_LOCAL_DATA", "PREVIEW_INIT",
    "PROGRESS_BAR_UPDATE_PROGRESS", "SET_GAME_STORAGE", "SET_TRANSITION_IMAGE"
];

// Emitted by client/ but unhandled in the build: iso-functional behaviour is nothing.
export const INERT_TYPES = [
    "ADD_BLIP", "INIT_WELCOME", "REMOVE_STORAGE", "SEND_STORAGE",
    "SET_CONTEXT_DATA", "UPDATE_ASPECT_RATIO"
];
