import * as bus from "./core/bus.js";
import { register as registerGameScreen } from "./components/game-screen.js";
import { register as registerNotify } from "./components/notify.js";
import { register as registerMinimapData } from "./components/minimap-data.js";
import { register as registerDefaultNotify } from "./components/default-notify.js";
import { register as registerPerspective } from "./components/perspective.js";
import { register as registerTextUI } from "./components/textui.js";
import { register as registerProgressBar } from "./components/progressbar.js";
import { register as registerHelpNotify } from "./components/helpnotify.js";
import { register as registerHud } from "./components/hud.js";
import { register as registerCarHud } from "./components/carhud.js";
import { register as registerVoice } from "./components/voice.js";
import { register as registerWeaponIndicator } from "./components/weapon-indicator.js";
import { register as registerStreetLabel } from "./components/streetlabel.js";
import { register as registerChat } from "./components/chat.js";
import { register as registerMenu } from "./components/menu.js";
import { register as registerGameMenu } from "./components/game-menu.js";
import { register as registerMainMenu } from "./components/main-menu.js";
import { register as registerPauseMenu } from "./components/pause-menu.js";
import { register as registerSettingsColor } from "./components/settings-color.js";
import { register as registerSettingsHud } from "./components/settings-hud.js";
import { register as registerSettingsCarHud } from "./components/settings-carhud.js";
import { register as registerSettingsNotify } from "./components/settings-notify.js";
import { register as registerSettingsProgressBar } from "./components/settings-progressbar.js";
import { register as registerSettingsHelpNotify } from "./components/settings-helpnotify.js";
import { register as registerSettingsMisc } from "./components/settings-misc.js";
import { register as registerPositionScreen } from "./components/position-screen.js";
import { register as registerMusic } from "./components/music.js";
import { register as registerStagger } from "./components/stagger.js";
import { register as registerWelcome } from "./components/welcome.js";
import { register as registerWelcomeMusic } from "./components/welcome-music.js";
import { register as registerWelcomePresets } from "./components/welcome-presets.js";
import { register as registerWelcomeCustomize } from "./components/welcome-customize.js";
import { register as registerPreviewScreen } from "./components/preview-screen.js";

// Components register their handlers here, then the bus opens the message port.
registerGameScreen(bus);
registerNotify(bus);
registerMinimapData(bus);
registerDefaultNotify(bus);
registerPerspective(bus);
registerTextUI(bus);
registerProgressBar(bus);
registerHelpNotify(bus);
registerHud(bus);
registerCarHud(bus);
registerVoice(bus);
registerWeaponIndicator(bus);
registerStreetLabel(bus);
registerChat(bus);
registerMenu(bus);
registerGameMenu(bus);
registerMainMenu(bus);
registerPauseMenu(bus);
registerSettingsColor(bus);
registerSettingsHud(bus);
registerSettingsCarHud(bus);
registerSettingsNotify(bus);
registerSettingsProgressBar(bus);
registerSettingsHelpNotify(bus);
registerSettingsMisc(bus);
registerPositionScreen(bus);
registerMusic(bus);
registerStagger(bus);
registerWelcome(bus);
registerWelcomeMusic(bus);
registerWelcomePresets(bus);
registerWelcomeCustomize(bus);
registerPreviewScreen(bus);

bus.start();
